apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "jmuhia80@gmail.com"
    privateKeySecretRef:
      name: acme-clusterissuer
    http01: {}
