// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: dummer/idl/dummer.proto

package dummer_gen

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	dummy_gen "github.com/veganafro/mono/dummy_gen"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_dummer_idl_dummer_proto protoreflect.FileDescriptor

var file_dummer_idl_dummer_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x2f, 0x69, 0x64, 0x6c, 0x2f, 0x64, 0x75, 0x6d,
	0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x75, 0x6d, 0x6d, 0x65,
	0x72, 0x5f, 0x67, 0x65, 0x6e, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2f, 0x69, 0x64, 0x6c, 0x2f, 0x64,
	0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x61, 0x0a, 0x0d, 0x44, 0x75,
	0x6d, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x17, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x5f,
	0x67, 0x65, 0x6e, 0x2e, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x44, 0x75, 0x6d,
	0x6d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0b, 0x22, 0x06, 0x2f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x3a, 0x01, 0x2a, 0x42, 0x26, 0x5a,
	0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x65, 0x67, 0x61,
	0x6e, 0x61, 0x66, 0x72, 0x6f, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x65,
	0x72, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_dummer_idl_dummer_proto_goTypes = []interface{}{
	(*dummy_gen.DummyRequest)(nil),  // 0: dummy_gen.DummyRequest
	(*dummy_gen.DummyResponse)(nil), // 1: dummy_gen.DummyResponse
}
var file_dummer_idl_dummer_proto_depIdxs = []int32{
	0, // 0: dummer_gen.DummerService.GetWorld:input_type -> dummy_gen.DummyRequest
	1, // 1: dummer_gen.DummerService.GetWorld:output_type -> dummy_gen.DummyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dummer_idl_dummer_proto_init() }
func file_dummer_idl_dummer_proto_init() {
	if File_dummer_idl_dummer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dummer_idl_dummer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dummer_idl_dummer_proto_goTypes,
		DependencyIndexes: file_dummer_idl_dummer_proto_depIdxs,
	}.Build()
	File_dummer_idl_dummer_proto = out.File
	file_dummer_idl_dummer_proto_rawDesc = nil
	file_dummer_idl_dummer_proto_goTypes = nil
	file_dummer_idl_dummer_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DummerServiceClient is the client API for DummerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DummerServiceClient interface {
	GetWorld(ctx context.Context, in *dummy_gen.DummyRequest, opts ...grpc.CallOption) (*dummy_gen.DummyResponse, error)
}

type dummerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDummerServiceClient(cc grpc.ClientConnInterface) DummerServiceClient {
	return &dummerServiceClient{cc}
}

func (c *dummerServiceClient) GetWorld(ctx context.Context, in *dummy_gen.DummyRequest, opts ...grpc.CallOption) (*dummy_gen.DummyResponse, error) {
	out := new(dummy_gen.DummyResponse)
	err := c.cc.Invoke(ctx, "/dummer_gen.DummerService/GetWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DummerServiceServer is the server API for DummerService service.
type DummerServiceServer interface {
	GetWorld(context.Context, *dummy_gen.DummyRequest) (*dummy_gen.DummyResponse, error)
}

// UnimplementedDummerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDummerServiceServer struct {
}

func (*UnimplementedDummerServiceServer) GetWorld(context.Context, *dummy_gen.DummyRequest) (*dummy_gen.DummyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorld not implemented")
}

func RegisterDummerServiceServer(s *grpc.Server, srv DummerServiceServer) {
	s.RegisterService(&_DummerService_serviceDesc, srv)
}

func _DummerService_GetWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dummy_gen.DummyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DummerServiceServer).GetWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dummer_gen.DummerService/GetWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DummerServiceServer).GetWorld(ctx, req.(*dummy_gen.DummyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DummerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dummer_gen.DummerService",
	HandlerType: (*DummerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorld",
			Handler:    _DummerService_GetWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dummer/idl/dummer.proto",
}
