load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

## BEGIN build_bazel_rules_android ##

RULES_ANDROID_VERSION = "0.1.1"
RULES_ANDROID_SHA = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806"

http_archive(
    name = "build_bazel_rules_android",
    sha256 = RULES_ANDROID_SHA,
    strip_prefix = "rules_android-%s" % RULES_ANDROID_VERSION,
    type = "zip",
    urls = ["https://github.com/bazelbuild/rules_android/archive/v%s.zip" % RULES_ANDROID_VERSION],
)

load("@build_bazel_rules_android//android:rules.bzl", "android_sdk_repository")
load("@build_bazel_rules_android//android:rules.bzl", "android_ndk_repository")

android_sdk_repository(
    name = "androidsdk",
    api_level = 30,
    build_tools_version = "30.0.3",
)

android_ndk_repository(
    name = "androidndk",
    api_level = 29,
)

## END build_bazel_rules_android ##

## BEGIN io_bazel_rules_kotlin ##

RULES_KOTLIN_VERSION = "legacy-1.3.0"
RULES_KOTLIN_SHA = "4fd769fb0db5d3c6240df8a9500515775101964eebdf85a3f9f0511130885fde"

http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = RULES_KOTLIN_SHA,
    strip_prefix = "rules_kotlin-%s" % RULES_KOTLIN_VERSION,
    type = "zip",
    urls = ["https://github.com/bazelbuild/rules_kotlin/archive/%s.zip" % RULES_KOTLIN_VERSION],
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")

kotlin_repositories()
kt_register_toolchains()

## END io_bazel_rules_kotlin ##

## Begin robolectric ##

ROBOLECTRIC_VERSION = "4.4"
ROBOLECTRIC_SHA = "f217e945d531828abced835ca467481827549250d57ae1b511899901cc4aeed9"

http_archive(
    name = "robolectric",
    sha256 = ROBOLECTRIC_SHA,
    strip_prefix = "robolectric-bazel-%s" % ROBOLECTRIC_VERSION,
    type = "zip",
    urls = ["https://github.com/robolectric/robolectric-bazel/archive/%s.zip" % ROBOLECTRIC_VERSION],
)

load("@robolectric//bazel:robolectric.bzl", "robolectric_repositories")

robolectric_repositories()

## End robolectric ##

## Begin rules_jvm_external ##

RULES_JVM_EXTERNAL_VERSION = "3.3"
RULES_JVM_EXTERNAL_SHA = "d85951a92c0908c80bd8551002d66cb23c3434409c814179c0ff026b53544dab"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_VERSION,
    type = "zip",
    urls = ["https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_VERSION],
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "androidx.appcompat:appcompat:1.2.0",
        "androidx.core:core-ktx:1.3.1",
        "androidx.constraintlayout:constraintlayout:2.0.1",
        "androidx.test:monitor:1.2.0",
        "androidx.test.espresso:espresso-core:3.3.0",
        "androidx.test.ext:junit:1.1.2",
        "junit:junit:4.12",
        "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.61",
        "org.robolectric:robolectric:4.4",
    ],
    fetch_sources = True,
    repositories = [
        "https://jcenter.bintray.com",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)

## End rules_jvm_external ##
