apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
  namespace: vault
spec:
  secretName: vault-tls
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - vault.vault.svc
  ipAddresses:
    - 127.0.0.1
