workspace(
    name = "veganafro_mono_server",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

## Begin rules_proto ##

RULES_PROTO_SHA = "602e7161d9195e50246177e7c55b2f39950a9cf7366f74ed5f22fd45750cd208"
RULES_PROTO_TAG = "97d8af4dc474595af3900dd85cb3a29ad28cc313"

http_archive(
    name = "rules_proto",
    sha256 = RULES_PROTO_SHA,
    strip_prefix = "rules_proto-%s" % RULES_PROTO_TAG,
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/%s.tar.gz" % RULES_PROTO_TAG,
        "https://github.com/bazelbuild/rules_proto/archive/%s.tar.gz" % RULES_PROTO_TAG,
    ],
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()
rules_proto_toolchains()

## End rules_proto ##

## Begin io_bazel_rules_go ##

RULES_GO_SHA = "7904dbecbaffd068651916dce77ff3437679f9d20e1a7956bff43826e7645fcc"
RULES_GO_VERSION = "0.25.1"

http_archive(
    name = "io_bazel_rules_go",
    sha256 = RULES_GO_SHA,
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v{}/rules_go-v{}.tar.gz".format(
            RULES_GO_VERSION, RULES_GO_VERSION
        ),
        "https://github.com/bazelbuild/rules_go/releases/download/v{}/rules_go-v{}.tar.gz".format(
            RULES_GO_VERSION, RULES_GO_VERSION
        ),
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()
go_register_toolchains(version = "1.14")

## End io_bazel_rules_go ##

## Begin bazel_gazelle ##

BAZEL_GAZELLE_SHA = "d4113967ab451dd4d2d767c3ca5f927fec4b30f3b2c6f8135a2033b9c05a5687"
BAZEL_GAZELLE_VERSION = "0.22.0"

http_archive(
    name = "bazel_gazelle",
    sha256 = BAZEL_GAZELLE_SHA,
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v{}/bazel-gazelle-v{}.tar.gz".format(
            BAZEL_GAZELLE_VERSION, BAZEL_GAZELLE_VERSION
        ),
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v{}/bazel-gazelle-v{}.tar.gz".format(
            BAZEL_GAZELLE_VERSION, BAZEL_GAZELLE_VERSION
        ),
    ],
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()

## End bazel_gazelle ##

## Begin com_google_protobuf ##

COM_GOOGLE_PROTOBUF_VERSION = "3.13"
COM_GOOGLE_PROTOBUF_SHA = "9748c0d90e54ea09e5e75fb7fac16edce15d2028d4356f32211cfa3c0e956564"

http_archive(
    name = "com_google_protobuf",
    sha256 = COM_GOOGLE_PROTOBUF_SHA,
    strip_prefix = "protobuf-%s" % COM_GOOGLE_PROTOBUF_VERSION,
    urls = [
        "https://github.com/protocolbuffers/protobuf/archive/v%s.zip" % COM_GOOGLE_PROTOBUF_VERSION
    ],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

## End com_google_protobuf ##

## Begin gRPC dependecies ##

GRPC_SUM = "h1:SfXqXS5hkufcdZ/mHtYCh53P2b+92WQq/DZcKLgsFRs="
GRPC_VERSION = "v1.31.1"

go_repository(
    name = "org_golang_google_grpc",
    build_file_proto_mode = "disable",
    importpath = "google.golang.org/grpc",
    sum = "%s" % GRPC_SUM,
    version = "%s" % GRPC_VERSION,
)

NET_SUM = "h1:MXfv8rhZWmFeqX3GNZRsd6vOLoaCHjYEX3qkRo3YBUA="
NET_VERSION = "v0.0.0-20200904194848-62affa334b73"

go_repository(
    name = "org_golang_x_net",
    importpath = "golang.org/x/net",
    sum = "%s" % NET_SUM,
    version = "%s" % NET_VERSION,
)

TEXT_SUM = "h1:cokOdA+Jmi5PJGXLlLllQSgYigAEfHXJAERHVMaCc2k="
TEXT_VERSION = "v0.3.3"

go_repository(
    name = "org_golang_x_text",
    importpath = "golang.org/x/text",
    sum = "%s" % TEXT_SUM,
    version = "%s" % TEXT_VERSION,
)

## End gRPC dependencies ##

## Begin grpc-gateway dependencies ##

GRPC_GATEWAY_SUM = "h1:Nk5kuHrnWUTf/0GL1a/vchH/om9Ap2/HnVna+jYZgTY="
GRPC_GATEWAY_VERSION = "v1.14.7"

go_repository(
    name = "com_github_grpc_ecosystem_grpc_gateway",
    importpath = "github.com/grpc-ecosystem/grpc-gateway",
    sum = "%s" % GRPC_GATEWAY_SUM,
    version = "%s" % GRPC_GATEWAY_VERSION,
)

GRPC_GATEWAY_V2_SUM = "h1:IvO4FbbQL6n3v3M1rQNobZ61SGL0gJLdvKA5KETM7Xs="
GRPC_GATEWAY_V2_VERSION = "v2.3.0"

go_repository(
    name = "com_github_grpc_ecosystem_grpc_gateway_v2",
    importpath = "github.com/grpc-ecosystem/grpc-gateway/v2",
    sum = "%s" % GRPC_GATEWAY_V2_SUM,
    version = "%s" % GRPC_GATEWAY_V2_VERSION,
)

GLOG_COMMIT = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

go_repository(
    name = "com_github_golang_glog",
    commit = "%s" % GLOG_COMMIT,
    importpath = "github.com/golang/glog",
)

YAML_COMMIT = "25d852aebe32c875e9c044af3eef9c7dc6bc777f"

go_repository(
    name = "com_github_ghodss_yaml",
    commit = "%s" % YAML_COMMIT,
    importpath = "github.com/ghodss/yaml",
)

YAML_V2_COMMIT = "0b1645d91e851e735d3e23330303ce81f70adbe3"

go_repository(
    name = "in_gopkg_yaml_v2",
    commit = "%s" % YAML_V2_COMMIT,
    importpath = "gopkg.in/yaml.v2",
)

## End grpc-gateway dependencies ##

## Begin rules_docker ##

RULES_DOCKER_SHA = "95d39fd84ff4474babaf190450ee034d958202043e366b9fc38f438c9e6c3334"
RULES_DOCKER_VERSION = "0.16.0"

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = RULES_DOCKER_SHA,
    strip_prefix = "rules_docker-%s" % RULES_DOCKER_VERSION,
    urls = [
        "https://github.com/bazelbuild/rules_docker/releases/download/v{}/rules_docker-v{}.tar.gz".format(
            RULES_DOCKER_VERSION, RULES_DOCKER_VERSION
        )
    ],
)

load("@io_bazel_rules_docker//repositories:repositories.bzl", container_repositories = "repositories")

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("@io_bazel_rules_docker//container:container.bzl", "container_pull")

container_pull(
    name = "bazel_3_5_0",
    # 'tag' is also supported, but digest is encouraged for reproducibility.
    digest = "sha256:ace9881e6e9c5d48b5fd637321361aeffe54000265894a65f7d818dc1065bd80",
    registry = "l.gcr.io",
    repository = "google/bazel",
)

## End rules_docker ##

## Begin rules_pkg ##

RULES_PKG_SHA = "038f1caa773a7e35b3663865ffb003169c6a71dc995e39bf4815792f385d837d"
RULES_PKG_VERSION = "0.4.0"

http_archive(
    name = "rules_pkg",
    sha256 = RULES_PKG_SHA,
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/{}/rules_pkg-{}.tar.gz".format(
            RULES_PKG_VERSION, RULES_PKG_VERSION
        ),
        "https://github.com/bazelbuild/rules_pkg/releases/download/{}/rules_pkg-{}.tar.gz".format(
            RULES_PKG_VERSION, RULES_PKG_VERSION
        ),
    ],
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()

## End rules_pkg ##
