apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "jeremy@fjarm.xyz"
    privateKeySecretRef:
      name: acme-clusterissuer-secret
    solvers:
    # SEE: https://cert-manager.io/docs/configuration/acme/http01/#configuring-the-http01-ingress-solver
    - http01:
        ingress:
          class: nginx
