android_local_test(
    name = "app_test",
    manifest = "AndroidManifest.xml",
    test_class = "com.veganafro.mono.ExampleInstrumentedTest",
    deps = [
        "//app/src/androidTest/java/com/veganafro/mono:app_test_lib",
        "@maven//:org_robolectric_robolectric",
        "@robolectric//bazel:android-all",
    ],
)
