apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummer
  namespace: dummer
spec:
  selector:
    matchLabels:
      app: dummer
  replicas: 1
  template:
    metadata:
      labels:
        app: dummer
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service-upstreams: 'dummy:8000'
    spec:
      serviceAccountName: dummer
      containers:
      - name: dummer
        image: veganafro/dummer_image:dev
        ports:
        - containerPort: 8001
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
