apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  namespace: dummy
spec:
  selector:
    matchLabels:
      app: dummy
  replicas: 1
  template:
    metadata:
      labels:
        app: dummy
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      serviceAccountName: dummy
      containers:
      - name: dummy
        image: veganafro/dummy_image:dev
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 2048Mi
            cpu: "2"
