apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  namespace: dummy
spec:
  selector:
    matchLabels:
      app: dummy
  replicas: 1
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
      - name: dummy
        image: veganafro/dummy_image:dev
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 1024Mi
            cpu: "2"
